version: '3.8'  # Specify the version

services:  
  yamcs_link:
    build:
      context: ./yamcs_link
    volumes:
      - mdb_shared:/mdb_shared  # Shared volume for MDB files
    network_mode: "host" #Easier for a test

  yamcs_server:
    build:
      context: ./yamcs_server
    volumes:
      - mdb_shared:/mdb_shared  # Access to the same shared volume
    network_mode: "host"

volumes:  # Define volumes
  mdb_shared:  # Define a volume for shared data between containers
